name: build

env:
  configuration: Release
  dotnet_version: 5.0.x
  project_data: kamafi.core.data
  project_services: kamafi.core.services
  project_middleware: kamafi.core.middleware

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}
      
    - name: build data
      run: dotnet build -c ${{ env.configuration }} ${{env.project_data }} --no-restore

    - name: build services
      run: dotnet build -c ${{ env.configuration }} ${{env.project_services }} --no-restore
      
    - name: build middleware
      run: dotnet build -c ${{ env.configuration }} ${{env.project_middleware }} --no-restore
      