name: publish packages

env:
  configuration: Release
  project_data: kamafi.core.data
  project_middleware: kamafi.core.middleware
  output_path: app/publish

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: build solution
      run: dotnet build -c ${{ env.configuration }}
          
    - name: generate packages
      run: |
        cd ${{ env.project_data }}
        dotnet pack -c ${{ env.configuration }} -o out
        cd ..
        cd ${{ env.project_middleware }}
        dotnet pack -c ${{ env.configuration }} -o out

    - name: push
      run: |
        dotnet nuget push -s ./${{ env.project_data }}/out/*.nupkg --skip-duplicate -n true -k ${{ secrets.PACKAGE_TOKEN }}
        dotnet nuget push -s ./${{ env.project_middleware }}/out/*.nupkg --skip-duplicate -n true -k ${{ secrets.PACKAGE_TOKEN }}
